#!/bin/bash

set -e

dc-spell "$1"
dc-linkchecker "$1"
dc-proselint "$1"
dc-style "$1"

# sudo apt install aspell
# sudo apt install diction
# sudo apt install python3-proselint
# sudo apt install pandoc
# sudo apt install linkchecker
